server {
    listen 9987 udp reuseport;
    proxy_timeout 30s;
    proxy_pass teamspeak.dmz:9987;
}

server {
    listen 10011 reuseport;
    proxy_timeout 30s;
    proxy_pass teamspeak.dmz:30033;
}

server {
    listen 30033 reuseport;
    proxy_timeout 30s;
    proxy_pass teamspeak.dmz:30033;
}
